Failed attempt to add a SubgraphWccs::to_parts() that returns something serializable
```
error[E0599]: the function or associated item `deserialize_eps` exists for struct `SubgraphWccsState`, but its trait bounds were not satisfied
   --> stdlib-rs/tests/connectivity.rs:301:51
    |
301 |       let deserialized_state = <SubgraphWccsState>::deserialize_eps(&data)?;
    |                                                     ^^^^^^^^^^^^^^^ function or associated item cannot be called on `SubgraphWccsState` due to unsatisfied trait bounds
    |
   ::: /home/dev/swh-environment/swh-graph/stdlib-rs/src/connectivity.rs:29:1
    |
29  | / pub struct SubgraphWccsState<
30  | |     N: MonotoneContractionBackend = EfSeqDict,
31  | |     C: AsRef<[NodeId]> = Box<[usize]>,
32  | |     S: std::borrow::Borrow<Sccs<C>> = Sccs<C>,
33  | | > {
    | |_- doesn't satisfy `_: DeserializeInner` or `_: Deserialize`
    |
    = note: the following trait bounds were not satisfied:
            `swh_graph_stdlib::connectivity::SubgraphWccsState: epserde::deser::DeserializeInner`
            which is required by `swh_graph_stdlib::connectivity::SubgraphWccsState: epserde::deser::Deserialize`
            `&swh_graph_stdlib::connectivity::SubgraphWccsState: epserde::deser::DeserializeInner`
            which is required by `&swh_graph_stdlib::connectivity::SubgraphWccsState: epserde::deser::Deserialize`
            `&mut swh_graph_stdlib::connectivity::SubgraphWccsState: epserde::deser::DeserializeInner`
            which is required by `&mut swh_graph_stdlib::connectivity::SubgraphWccsState: epserde::deser::Deserialize`
```